### ISSUE TITLE
v5 Wishlist & Roadmap

### ISSUE THREAD

**Issue by bersLucas** [bersLucas/liljs#23]
* [ ] Split up propTypes to use `includes` for readability
* [ ] Re-write `lil-list` to use `<templates>`, will fix #3 & #2 and make `lil-index` (potentially) redundant
  * [ ] Try to replace `lil-list-text` with a templating engine, à la [styled-components ](https://github.com/styled-components/styled-components)
* [ ] Combine `lil-bind` and `lil-bind-from`
```html
<!-- before -->
<input lil-bind="propName" lil-bind-from="value">

<!-- after -->
<input lil-bind-value="propName">
```
* [ ] Use `class` for each property, easier and more readable initialization
